# Setting up the pod to use the Kubernetes secret object as environmental variables
# By default; specific secret must exist and the requested key
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: gcr.io/abiding-cedar-359014/microservice-app-template-auth:latest
        ports:
        - containerPort: 80
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: authdb-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authdb-secret
              key: password
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"