apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deployment
  labels:
    app: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: gcr.io/abiding-cedar-359014/microservice-app-template-greeting:latest
        ports:
        - containerPort: 80
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"