services:

  # Logical services
  api-gateway:
    image: ashinebourne/api-gateway:latest
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=auth-blacklist
      - REDIS_PASSWORD=password123
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=secret
    volumes:
      - ./gateway.conf.yaml:/gateway.conf.yaml
    depends_on:
      - auth-blacklist
  user-management:
    image: ashinebourne/user-auth:latest
    ports:
      - "8001:8000"
    environment:
      - JWT_SECRET_KEY=secret
      - JWT_TOKEN_EXP_MIN=60
      - DB_HOST=user-db
      - DB_PORT=27017
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=user_management
      - REDIS_HOST=auth-blacklist
      - REDIS_PASSWORD=password123
      - REDIS_PORT=6379
    depends_on:
      - user-db
  hello-user:
    build:
      context: ./backends/hello-user
    ports:
      - "8002:8000"
    depends_on:
      - api-gateway

  # State services (databases, caches, etc.)
  user-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=user_management
  auth-blacklist:
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password123
  # Dev tools
  # db-gui:
  #   image: mongo-express
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: secret
  #     ME_CONFIG_MONGODB_SERVER: user-db
  #   restart: always
